#!/bin/bash

function fail {
	echo "ERROR: $1" >&2
	exit 1
}

function configure {

#Altera a senha do cn=admin,cn=config

	ldapmodify -Y EXTERNAL -H ldapi:/// <<-_EOF
		dn: olcDatabase={0}config,cn=config
		replace: olcRootPW
		olcRootPW: $CONF_ROOTPW
		_EOF

#Adiociona todos os schemas necessarios para a federação		

	tar xzf ldapDocer.tar.gz
	mv base.ldif grupos.ldif /initdb.d

	ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif  -c
    	ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif -c
    	ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif -c
    	ldapadd -Y EXTERNAL -H ldapi:/// -f breduperson.ldif -c
    	ldapadd -Y EXTERNAL -H ldapi:/// -f eduperson.ldif -c
    	ldapadd -Y EXTERNAL -H ldapi:/// -f samba.ldif -c
    	ldapadd -Y EXTERNAL -H ldapi:/// -f radius-ldap.ldif -c
    	ldapadd -Y EXTERNAL -H ldapi:/// -f schac-20061212-1.ldif -c

#Libera o acesso aos itens de monitoramento do LDAP.	

	ldapmodify -Y EXTERNAL -H ldapi:/// <<-_EOF
		dn: olcDatabase={1}monitor,cn=config
		changetype: modify
		replace: olcAccess
		olcAccess: {0}to * by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth"
  			read by dn.base="cn=admin,$CONF_BASEDN" read by * none
	_EOF
	
#Altera os atributos de permissão do ramo do diretorio.

	ldapmodify -Y EXTERNAL -H ldapi:/// <<-_EOF
		dn: olcDatabase={2}hdb,cn=config
		changetype: modify
		replace: olcSuffix
		olcSuffix: $CONF_BASEDN
	
		dn: olcDatabase={2}hdb,cn=config
		changetype: modify
		replace: olcRootDN
		olcRootDN: cn=admin,$CONF_BASEDN

		dn: olcDatabase={2}hdb,cn=config
		changetype: modify
		replace: olcRootPW
		olcRootPW: $CONF_ROOTPW
		
		_EOF

#Altera as ACLS do diretorio.
	ldapmodify -Y EXTERNAL -H ldapi:/// <<-_EOF
		dn: olcDatabase={2}hdb,cn=config
		changetype: modify
		add: olcAccess
		olcAccess: {0}to attrs=userPassword by dn="cn=admin,$CONF_BASEDN" write by anonymous auth by self write by * none
		olcAccess: {1}to dn.base="" by * read
		olcAccess: {2}to * by dn="cn=admin,$CONF_BASEDN" write by * read	
	_EOF

# Configurando o uso de grupos no ldap.

	ldapadd -Y EXTERNAL -H ldapi:/// <<-_EOF
		dn: cn=module,cn=config
		objectClass: olcModuleList
		cn: module
		olcModulepath: /usr/lib64/openldap
		olcModuleload: memberof.la
		olcModuleload: refint.la	

	_EOF
	
	ldapadd -Y EXTERNAL -H ldapi:/// <<-_EOF
		dn: olcOverlay={0}memberof,olcDatabase={2}hdb,cn=config
		objectClass: olcConfig
		objectClass: olcMemberOf
		objectClass: olcOverlayConfig
		objectClass: top
		olcOverlay: memberof
		olcMemberOfDangling: ignore
		olcMemberOfRefInt: TRUE
		olcMemberOfGroupOC: groupOfNames
		olcMemberOfMemberAD: member
		olcMemberOfMemberOfAD: memberOf
	_EOF

#Criando certificados autoassinados e adicioando o nslcd

	sh GerarCertificadosOPENSSL.sh


#Configurando o SSL do ldap.
	mkdir /config/certs && cd /config/certs
	cp /etc/pki/tls/certs/* /config/certs
	chown ldap. /config/certs/* 
       
	ldapmodify -Y EXTERNAL -H ldapi:/// <<-_EOF
		dn: cn=config
		changetype: modify
		add: olcTLSCACertificateFile
		olcTLSCACertificateFile: /config/certs/ca-bundle.crt
		-
		replace: olcTLSCertificateFile
		olcTLSCertificateFile: /config/certs/server.crt
		-
		replace: olcTLSCertificateKeyFile
		olcTLSCertificateKeyFile: /config/certs/server.key
	_EOF

	return $?
}

chown -R ldap:ldap /config /data || fail "Cannot change owner of supplied volumes."

if [[ ! -d '/config/cn=config' ]] ; then
	# supplied empty config volume, use defaults
	[[ -z "$CONF_ROOTPW" ]] && fail "No existing config found and CONF_ROOTPW not given."
	[[ -z "$CONF_BASEDN" ]] && fail "No existing config found and CONF_BASEDN not given."
	[[ "${CONF_ROOTPW:0:1}" == '{' ]] || CONF_ROOTPW=`slappasswd -s "$CONF_ROOTPW"`
	cp -a /etc/openldap/slapd.d/. /config/
	echo "Starting temporary slapd to modify dynamic config."
	/usr/sbin/slapd -F /config -u ldap -g ldap -h 'ldapi:// ldap://' -d -64 &
	dpid=$!

	CONFIGURED=0
	for i in {1..10} ; do
		sleep 1
		configure && CONFIGURED=1
		[[ $CONFIGURED -eq 1 ]] && break
	done
	[[ $CONFIGURED -ne 1 ]] && fail "Unable to configure slapd (timeout?)."

	echo "Loading LDIF files from /initdb.d"
	find /initdb.d -maxdepth 1 -iname '*.ldif' | sort | while read filename ; do
		echo "* processing $filename"
#		ldapadd -Y EXTERNAL -H ldapi:/// < "$filename"
#Populando a base e os grupos.
		ldapadd -D cn=admin,$CONF_BASEDN -w $CONF_ROOTPW1  < "$filename" -c

	done

	echo "Stopping temporary slapd."
	# set timeout
	function timeout {
		kill -KILL $dpid
		fail "Timeout stopping temporary slapd instance."
	}
	trap timeout ALRM
	sleep 5 && kill -ALRM $$ &
	# kill slapd
	kill $dpid
	# wait for slapd exit (or timeout)
	wait $dpid
	# clear timeout
	kill %+
	trap - ALRM
fi

echo "Starting slapd."
exec /usr/sbin/slapd -F /config -u ldap -g ldap -h 'ldapi:// ldap://' -d 64
